### ISSUE TITLE
Page Not Found (Fog::JSON::DecodeError)

### ISSUE THREAD

**Issue by derks** [StackPointCloud/fog-packet#33]
Using Vagrant Packet Plugin, which in-turn uses `fog-packet`... this same config has been online for days, but today I am getting the following:

```
/opt/vagrant/embedded/lib/ruby/2.4.0/json/common.rb:156:in `parse': 751: unexpected token at 'page not found (Fog::JSON::DecodeError)
'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/json/common.rb:156:in `parse'
	from /opt/vagrant/embedded/gems/2.2.6/gems/multi_json-1.14.0/lib/multi_json/adapters/json_common.rb:14:in `load'
	from /opt/vagrant/embedded/gems/2.2.6/gems/multi_json-1.14.0/lib/multi_json/adapter.rb:21:in `load'
	from /opt/vagrant/embedded/gems/2.2.6/gems/multi_json-1.14.0/lib/multi_json.rb:122:in `load'
	from /Users/derks/.vagrant.d/gems/2.4.9/gems/fog-json-1.2.0/lib/fog/json.rb:40:in `decode'
	from /Users/derks/.vagrant.d/gems/2.4.9/gems/fog-packet-1.0.1/lib/fog/compute/packet/compute.rb:281:in `request'
	from /Users/derks/.vagrant.d/gems/2.4.9/gems/fog-packet-1.0.1/lib/fog/compute/packet/requests/get_device.rb:7:in `get_device'
	from /Users/derks/.vagrant.d/gems/2.4.9/gems/fog-packet-1.0.1/lib/fog/compute/packet/models/devices.rb:16:in `get'
	from /Users/derks/.vagrant.d/gems/2.4.9/gems/vagrant-packet-0.1.6/lib/vagrant-packet/action/read_state.rb:26:in `read_state'
	from /Users/derks/.vagrant.d/gems/2.4.9/gems/vagrant-packet-0.1.6/lib/vagrant-packet/action/read_state.rb:17:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /Users/derks/.vagrant.d/gems/2.4.9/gems/vagrant-packet-0.1.6/lib/vagrant-packet/action/connect_packet.rb:24:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:238:in `action_raw'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:209:in `block in action'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:195:in `action'
	from /Users/derks/.vagrant.d/gems/2.4.9/gems/vagrant-packet-0.1.6/lib/vagrant-packet/provider.rb:34:in `state'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:532:in `state'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:146:in `initialize'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/vagrantfile.rb:81:in `new'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/vagrantfile.rb:81:in `machine'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:715:in `machine'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:213:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:212:in `map'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:212:in `with_target_vms'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/synced_folders/rsync/command/rsync_auto.rb:49:in `execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/cli.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/bin/vagrant:182:in `<main>'
```

Any help would be appreciated.

**Comment by derks** [comment]
Might have been a fluke, this is not happening currently.

**Comment by dmitryshagin** [comment]
Looks like a service degradation - they had stated some errors recently https://status.packet.com/
